# Site settings
title: Kenny Lay
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kenny Lay
user_description: I'm a Software Engineer from California, with some internship experience. As I am in my early career, I aim to build myself to become a strong and valuable asset.
user_title: Software Engineer
email: kxlay99@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: kenny-lay
github_username:  KennyXLay
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

